spring:
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    driverClassName: org.postgresql.Driver
    password: 123
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        jdbc:
          lob:
            non_contextual_creation: true
